name: Java CI for tutorial MS

on:
  push:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ./mvnw verify
    
    - if: ${{ github.ref == 'refs/heads/main'}}
      name: Build and publish the image
      run: |
        ./mvnw clean package jib:dockerBuild -DskipTests 
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/tutorial
